require("config.keymaps")
require("config.options")
require("config.lazy")
require("config.neovide")
require("config.language")
require("config.autocmd")
require("plugins.custom.statusline")
-- local discipline = require("config.discipline")
--
-- discipline.cowboy()
